### PR TITLE
Add sentry to blog

### PR DESCRIPTION
**Pull request by tbille**
# Summary

Add sentry config to blog 

# QA

- Create file `config.blog.yaml`:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn
  namespace: production
type: Opaque
data:
  blog-ubuntu-com: aHR0cHM6Ly9rZXk6c2VjcmV0QHNlbnRyeS5pcy5jYW5vbmljYWwuY29tLy8xCg==
```
- `microk8s.kubectl -f config.blog.yaml`
- `./qa-deploy --production blog.ubuntu.com --tag latest`
- Make sure pod has the right dsn (you can see it from the dashboard)

### CODE REVIEW

**Comment by tbille** [comment]
@nottrobin Unfortunatly we don't use this library. Talisker uses `raven` which is deprecated now  and requires to have this DSN format: `<key>:<secret>@sentry.io/<project>` 

I can't find it again, but I think this shouldn't be shared. I can put it in a secret for now, until talisker ugrades to use the latest version of sentry SDK

**Comment by nottrobin** [comment]
@tbille ah cool, yes I see you filed https://github.com/canonical-ols/talisker/issues/346 - thanks.

Yes, that old format contains a secret key. So yes that should be kept in a `Secret` rather than `ConfigMap`.

The only remaining question is - is it different for blog.ubuntu.com than it is for snapcraft.io? Or is it the same? 'cos if it's the same they should share the secret.

**Comment by tbille** [comment]
@nottrobin no there is on DSN per project.
Maybe I could make a secret containing all the DSNs?

**Comment by nottrobin** [comment]
@tbille hmm. Is it better to collect all sentry secrets together? Or to collect all blog.ubuntu.com secrets together? Or to keep every value in its own secret? It depends how they're going to be managed.

I suppose, if you were to update the SENTRY_DSN, it's fairly likely you'd want to update all the SENTRY_DSNs together. So maybe you're right, the best thing to do is to have one `sentry` secret with a `blog_dsn` value - does that sound good?

**Comment by tbille** [comment]
sounds good to me, I am making the update now.

**Comment by nottrobin** [comment]
Is it not allowed to be `blog-ubuntu-com_dsn`? Since `blog-ubuntu-com` is the exact name of the service & deployment.

**Comment by nottrobin** [comment]
Also I don't think you need `dsn` twice. Either it should be a secret called `sentry` and a key called `blog-ubuntu-com_dsn`, or should should be a secret called `sentry_dsn` and a key called `blog-ubuntu-com`.

**Pull request merged**
