### PR TITLE
Add tutorials.ubuntu.com config

### PR DESCRIPTION
**Pull request by WillMoggridge**
## Done
Added tutorials.ubuntu.com

## QA

``` bash
# Install VirtualBox if you haven't got it
sudo apt install virtualbox

# Install minikube if you haven't already
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

# Enable Ingress add-on
minikube addons enable ingress

# Get minkube running
minikube start
kubectl config set-context minikube  # To be on the safe side

# Deploy new configs to minikube
cat services/tutorials.ubuntu.com.yaml | sed 's|prod-comms.docker-registry.canonical.com/tutorials.ubuntu.com|canonicalwebteam/tutorials.ubuntu.com|' | sed 's|[:][$][{]TAG_TO_DEPLOY[}]||' | sed 's|replicas: 5|replicas: 1|' | kubectl apply --namespace staging --filename -
cat services/tutorials.ubuntu.com.yaml | sed 's|prod-comms.docker-registry.canonical.com/tutorials.ubuntu.com|canonicalwebteam/tutorials.ubuntu.com|' | sed 's|[:][$][{]TAG_TO_DEPLOY[}]||' | sed 's|replicas: 5|replicas: 1|' | kubectl apply --namespace production --filename -
kubectl apply --namespace staging --filename ingresses/staging/tutorials.staging.ubuntu.com.yaml
kubectl apply --namespace production --filename ingresses/production/tutorials.ubuntu.com.yaml

# Check everything deployed correctly
kubectl get ingress,service,deployment,pod --namespace staging  # Inspect staging elements
kubectl get ingress,service,deployment,pod --namespace production  # Inspect production elements

# Curl the site, check for 200 status
curl -I -H 'Host: tutorials.ubuntu.com' `minikube ip`
curl -I -H 'Host: tutorials.staging.ubuntu.com' `minikube ip`
```

### CODE REVIEW

**Comment by nottrobin** [comment]
I got an odd thing - pulling and running the image locally now works. Trying to do it through kubernetes, I see a page that returns a 200, but says "404: Page not found". I'll look more tomrorow and work out if it's my fault.

**Comment by WillMoggridge** [comment]
I have located the problem to the `es6-bundled` build. I could not track down the exact fix for it just yet but have created a PR to disable that build: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/409

I have also created a high priority issue to get it working: https://github.com/canonical-websites/tutorials.ubuntu.com/issues/410

**Comment by WillMoggridge** [comment]
I have updated the related PR and Docker Hub image to prevent the websocket error for HTTPS.

**Comment by tbille** [comment]
just ran what you added on your QA script
For staging and production I have this error:
`po/tutorials-ubuntu-com-6df5db96b5-ct9tm    0/1       CrashLoopBackOff   5          5m`

**Comment by WillMoggridge** [comment]
Sorry, I think I pushed up a docker image with the wrong port exposed. I have updated it and it deployed on my minikube.

**Pull request merged**
